ALTER TABLE characters ADD COLUMN IF NOT EXISTS total_costumes INTEGER DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS total_dances INTEGER DEFAULT 0;
ALTER TABLE characters ADD COLUMN IF NOT EXISTS total_secrets INTEGER DEFAULT 0;
